services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fendi_portfolio
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - proxy-tier

networks:
  proxy-tier:
    name: proxy-tier
    driver: bridge
